# Perceptron

In [3]:
from random import choice
from numpy import array, dot, random

In [2]:
# OR Logic
one_or_zero = lambda x: 0 if x < 0 else 1
training_data = [(array([0,0,1]), 0),
                 (array([0,1,1]), 1),
                 (array([1,0,1]), 1),
                 (array([1,1,1]), 1)]

weights = random.rand(3)
errors = []
learning_rate = 0.2
num_iterations = 100

for i in range(num_iterations):
    input, truth = choice(training_data)
    result = dot(weights, input)
    error = truth - one_or_zero(result)
    errors.append(error)
    weights += learning_rate*error*input
    
for x, _ in training_data:
    result = dot(x,weights)
    print("{}: {} -> {}".format(x[:2], result, one_or_zero(result)))

print(weights)

[0 0]: -0.13545008003623926 -> 0
[0 1]: 0.49234468917025787 -> 1
[1 0]: 0.7907123388990701 -> 1
[1 1]: 1.4185071081055673 -> 1
[ 0.92616242  0.62779477 -0.13545008]
